version: "3.8"

services:
  app:
    container_name: fastapi_app
    build: ./app
    ports:
      - 8000:8000
    volumes:
      # создаем volume, для хранения лог-файлов вне контейнера
      - app-logs:/logs

  log-shipper:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.12.0
    entrypoint: filebeat -e -strict.perms=false
    user: root
    volumes:
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      # подключаем volume с лог-файлами в контейнер
      - app-logs:/var/app/log

volumes:
  app-logs: